### ISSUE TITLE
VagrantCloud::Acount ignores username

### ISSUE THREAD

**Issue by tas50** [hashicorp/vagrant_cloud#42]
If you create a VagrantCloud::Acount object and set a username and then run a command like ensure_box the username is ignored and the box is created under the username of the token.

Example:
```ruby
conn = VagrantCloud::Account.new("bento", "1234")
```
After this I should be able to create a box and have it created under bento instead of my own username.

```ruby
conn.ensure_box('fedora-29')
```

Instead of having bento/fedora-29 created I get tas50/fedora-29 created. I can pass the username value as a param to ensure_box, but it should respect the default username set in the Account object.

**Comment by briancain** [comment]
@tas50 - I should mention also....this can be achieved now creating a `Box` class with your Account object too if you want to create a Box under the `bento` org.

**Comment by tas50** [comment]
@briancain It's been a while, but I circled back on this one. I'm still running into issues and maybe I'm just missing something fundamental with how the Vagrant Cloud works so hear me out. We have the bento organization and I'm on the owners team for that org. I've tried the following, but I still get an unauthorized error when I'm trying to interact with a box in the bento org.

```ruby
vc_account = VagrantCloud::Account.new("bento", ENV["VAGRANT_CLOUD_TOKEN"])
box = VagrantCloud::Box.new(vc_account, "oracle-6.10", "a box", "a box", ENV["VAGRANT_CLOUD_TOKEN"])
box.create_version("1.2.60")
```

```
VagrantCloud::ClientError: 401 Unauthorized - {"message"=>"Bad credentials"}
from /usr/local/lib/ruby/gems/2.6.0/gems/vagrant_cloud-2.0.2/lib/vagrant_cloud/client.rb:55:in `rescue in request'
Caused by RestClient::Unauthorized: 401 Unauthorized
from /usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response'
```

**Comment by briancain** [comment]
@tas50 - Apologies, this completely dropped off my radar and I'm sorry! So there is something that you are doing wrong with the Box initialize method. It's not very obvious _why_ it was failing, and I think we should at least warn the user or make the code docs clearer.

Essentially your initialization is ignoring an optional param that was left over from the original legacy implementation. There's a param that sets an internal var `@data` that you are missing....instead it should be:

```ruby
box = VagrantCloud::Box.new(vc_account, "oracle-6.10", nil, "a box", "a box", ENV["VAGRANT_CLOUD_TOKEN"])
```

https://github.com/hashicorp/vagrant_cloud/blob/73afaae87d6a7db080cb94b40a9080c956df3c88/lib/vagrant_cloud/box.rb#L12

The `nil` is a required param...where it's either nil or an existing `@data` hash. It's not too obvious, but that is what is going wrong :(

**Comment by briancain** [comment]
A good example of using this gem library might be the `publish` implementation in Vagrant:

https://github.com/hashicorp/vagrant/blob/fbe44f1f48918138efa7de4bf7a9cd163d9a91fb/plugins/commands/cloud/publish.rb#L97-L100

```ruby
account = VagrantPlugins::CloudCommand::Util.account(org, access_token, server_url)
box = VagrantCloud::Box.new(account, box_name, nil, options[:short_description], options[:description], access_token)
cloud_version = VagrantCloud::Version.new(box, version, nil, options[:version_description], access_token)
provider = VagrantCloud::Provider.new(cloud_version, provider_name, nil, options[:url], org, box_name, access_token)
```

**Comment by briancain** [comment]
I think that might of been your original issue too, perhaps? I just tried using my auth token to create a box on a different org, and it works as expected:

```ruby
3] pry(main)> account = VagrantCloud::Account.new("hashicorp-vagrant", vagrant_token)
=> #<VagrantCloud::Account:0x0000560cc4b07350
 @access_token="<TOKEN>",
 @client=#<VagrantCloud::Client:0x0000560cc4b07300 @access_token="<TOKEN>", @url_base="https://vagrantcloud.com/api/v1">,
 @username="hashicorp-vagrant">
[4] pry(main)> box = VagrantCloud::Box.new(account, "test", nil, "a box", "box", vagrant_token)
=> #<VagrantCloud::Box:0x0000560cc46a5c80
 @account=
  #<VagrantCloud::Account:0x0000560cc4b07350
   @access_token="<TOKEN>",
   @client=#<VagrantCloud::Client:0x0000560cc4b07300 @access_token="<TOKEN>", @url_base="https://vagrantcloud.com/api/v1">,
   @username="hashicorp-vagrant">,
 @client=#<VagrantCloud::Client:0x0000560cc46a5be0 @access_token="<TOKEN>", @url_base="https://vagrantcloud.com/api/v1">,
 @data=nil,
 @description="box",
 @name="test",
 @short_description="a box">
[5] pry(main)> box.create
RestClient.post "https://vagrantcloud.com/api/v1/boxes", "box[name]=test&box[username]=hashicorp-vagrant&box[is_private]=false&box[short_description]=a+box&box[description]=box", "Accept"=>"application/json", "Accept-Encoding"=>"gzip, deflate", "Authorization"=>"Bearer <TOKEN>", "Content-Length"=>"118", "Content-Type"=>"application/x-www-form-urlencoded", "User-Agent"=>"rest-client/2.0.2 (linux-gnu x86_64) ruby/2.5.3p105"
# => 200 OK | application/json 315 bytes
=> {"tag"=>"hashicorp-vagrant/test",
 "username"=>"hashicorp-vagrant",
 "name"=>"test",
 "private"=>false,
 "downloads"=>0,
 "created_at"=>"2019-03-06T17:17:29.585Z",
 "updated_at"=>"2019-03-06T17:17:29.585Z",
 "short_description"=>"a box",
 "description_markdown"=>"box",
 "description_html"=>"<p>box</p>\n",
 "current_version"=>nil,
 "versions"=>[]}
```

I'm going to go ahead and close this, but if you find that I'm missing something and there's an issue please let me know and I'll be happy to re-open and take a look!
