### ISSUE TITLE
Update param docs and or ensure `@data` param is properly set

### ISSUE THREAD

**Issue by briancain** [hashicorp/vagrant_cloud#48]
Issue #42 revealed that if a user accidentally sets the `@data` param on a class with something other than what it should be, it ends up ignoring any of the other valid auth data used to make requests. This issue should cover making it clear in the code docs that the param is required, and also make sure that param is properly set as a hash and not accidentally set as a string.

**Comment by chrisroberts** [comment]
Closing due to refactor
