### ISSUE TITLE
Vagrant Cloud Dashboard Performance

### ISSUE THREAD

**Issue by ladar** [hashicorp/vagrant_cloud#60]
I finally came off the road and resettled at home, complete with my own high speed connection. So I noticed a performance issue with the Vagrant Cloud. Specifically the home page loads almost instantly, but when I goto login, there is a significant delay. This morning it clocked in at 11 seconds. Almost all waiting for the server to respond. See the screenshot. 

I suspect I notice this more than most because of how many boxes I maintain, so that means more fetches on the backend. Hopefully you can optimize things a bit.

**Comment by ladar** [comment]
Screenshot with timing data.

![Screenshot from 2020-08-06 18-36-22](https://user-images.githubusercontent.com/1434008/89595141-5d573600-d819-11ea-9d5b-0d15669f457a.png)

**Comment by chrisroberts** [comment]
Hi,

An update with paginated results on the user dashboard was pushed out a bit ago so you shouldn't see this behavior anymore.

Cheers!
