### ISSUE TITLE
download_url entry of a provider is automatically set to point to vagrantcloud upon saving it

### ISSUE THREAD

**Issue by dcermak** [hashicorp/vagrant_cloud#68]
I am currently trying to use this gem to link an existing vagrant box that is hosted on an external server to Vagrant Cloud, but I'm running into the issue that upon saving the provider, the `download_url` entry is overwritten to point to a (non-existent) url on VagrantCloud.

The core of my linking script looks like this:
```ruby
def link_box(box_from_obs, org)
  matching_boxes = org.boxes.select { |b| b.name == box_from_obs['name'] }
  matching_box = nil

  if matching_boxes.empty?
    matching_box = org.add_box(box_from_obs['name'])
    matching_box.description = box_from_obs['description']
    matching_box.short_description = box_from_obs['short_description']
  elsif matching_boxes.length > 1
    raise "Got #{matching_boxes.length} matching boxes, but should have gotten at most one"
  else
    matching_box = matching_boxes[0]
  end

  matching_box.versions.each(&:delete)

  matching_box.versions = []
  matching_box.save

  box_from_obs['versions'].each do |version|
    ver = matching_box.add_version(version['version'])
    ver.description = version['description']

    version['providers'].each do |provider|
      prov = ver.add_provider(provider['name'])
      prov.url = provider['url']
      puts prov.inspect
    end

    ver.save
    ver.release
  end
  matching_box.save
end
```

where `org` is a VagrantCloud organization and `box_from_obs` is a hash serialized from json:
``` json
{
  "description": "Tumbleweed.x86_64 Vagrant Box",
  "name": "Tumbleweed.x86_64",
  "short_description": "Tumbleweed.x86_64 Vagrant Box",
  "versions": [
    {
      "description_html": "<p>Tumbleweed.x86_64 Vagrant images</p>\n",
      "description_markdown": "Tumbleweed.x86_64 Vagrant images\n",
      "providers": [
        {
          "name": "libvirt",
          "url": "http://download.opensuse.org/tumbleweed/appliances/Tumbleweed.x86_64-1.0-libvirt-Snapshot20201114.vagrant.libvirt.box"
        },
        {
          "name": "virtualbox",
          "url": "http://download.opensuse.org/tumbleweed/appliances/Tumbleweed.x86_64-1.0-virtualbox-Snapshot20201114.vagrant.virtualbox.box"
        }
      ],
      "status": "active",
      "version": "1.0.20201114"
    }
  ]
}
```

The issue is, that upon executing `ver.save` in `link_box`, the `download_url` field is automatically set to point to `https://vagrantcloud.com/<user>/boxes/<boxname>/versions/<version>/providers/<provider>.box`. This is invalid in this case, as I want this entry to not be present at all or to point to my original url.

How can I achieve this? I think I'm doing something silly here, as this shouldn't be happening.

**Comment by chrisroberts** [comment]
@dcermak Hi! The URL you are receiving is the expected box download URL. Regardless if boxes are hosted on Vagrant Cloud or on an external host, the box download URL will always be a Vagrant Cloud URL. The reason for this is it provides a unified way to provide download locations and it allows applying authentication restrictions if required. If you want to get the external URL, you can either:

* HEAD the download URL and extract the `Location` header value (needs authentication if required)
* Use the `original_url` from the provider information

On the second point, here's an example for getting that data when a provider is configured for external hosting:

```
2.5.0 :028 > VagrantCloud::Account.new.organization.boxes.detect{ |b| b.name == "new-test-box-2" }.versions.first.providers.first.tap{ |p| 
  puts "Download: #{p.download_url}"; 
  puts "Original: #{p.original_url}" 
}
Download: https://vagrantcloud.com/spox/boxes/new-test-box-2/versions/0.1.0/providers/qemu.box
Original: http://example.com/test/qemu.box
```

Hope that helps! If I misunderstood the problem you were encountering, or this didn't fully answer your question, please just let me know and I'll reopen this issue.

Cheers!

**Comment by dcermak** [comment]
Thanks for your reply @chrisroberts! I must confess that I have my trouble parsing your code example, as you appear to be using direct client and not the simple models as I am. Is it possible to achieve this kind of redirection via the simple models? If my ruby doesn't escape me, then there's no way how to set either `download_url` or `original_url` of a Provider, as both are immutable fields. So I guess I have to use the direct client?

**Comment by chrisroberts** [comment]
Apologies, I was running it via IRB to work against real data but the formatting is definitely lacking. The example is using the simple models interface. Here it is a little more cleaned up:

```ruby
# Create account connection
account = VagrantCloud::Account.new
# Grab default organization (same as: account.organization(name: "spox"))
organization = account.organization
# Get test box from organization
box = organization.boxes.detect do |b| 
  b.name == "new-test-box-2"
end
# Only have one version, so grab that version
version = box.versions.first
# Only one provider, so grab that provider
provider = version.providers.first

# Now we can print the data from the provider
puts "Download: #{provider.download_url}"
puts "Original: #{provider.original_url}" 
```

This gets the output: 

```
Download: https://vagrantcloud.com/spox/boxes/new-test-box-2/versions/0.1.0/providers/qemu.box
Original: http://example.com/test/qemu.box
```

The simple modeling matches up with the data returned from the REST API calls, so you can see in the docs here: https://www.vagrantup.com/vagrant-cloud/api#read-a-provider how the `provider.download_url` and `provider.original_url` match up with the JSON result being received from the API.

When setting the external URL for the provider (either to create it or to update it) the `url` field is used. In the model, we can see this here as it is flagged as mutable: https://github.com/hashicorp/vagrant_cloud/blob/main/lib/vagrant_cloud/box/provider.rb#L19

This matches up with the API which accepts a `url` parameter to update the external hosting location (which is the same for create too): https://www.vagrantup.com/vagrant-cloud/api#update-a-provider 

So, to update the external URL for the box provider (assuming a continuation of the code above so we have a `provider` variable) we would just do:

```ruby
provider.url = "https://example.org/my/new/qemu.box"
provider.save
````

If you're wanting something different than the above, please just let me know. And thanks for asking the questions! It's helping me write out a bit more usage documentation to clarify things as the README examples are admittedly pretty bare bones :slightly_smiling_face: 

Cheers!
